const LEGACY_KEY='eiram-closet-v1';
const DB_NAME='eiram-closet-db';
const DB_VERSION=1;
const STORE='app';
let state={closet:[],wishlist:[]};
let currentPhoto='';
const views=['closet','outfits','colour','wishlist','settings'];
const titleMap={closet:'My Closet',outfits:'Outfits',colour:'Colour Combinations',wishlist:'Wishlist',settings:'Settings'};
const wadaPalettes=[
{name:'Deep blue + warm ochre',keys:['navy','blue','indigo','denim'],colors:['#24334a','#c49045','#e7d8b1'],labels:['Deep blue','Warm ochre','Soft cream']},
{name:'Olive + dusty rose',keys:['olive','green','khaki','sage','moss'],colors:['#6f7154','#c8928d','#ead7c7'],labels:['Olive','Dusty rose','Warm beige']},
{name:'Burgundy + soft teal',keys:['burgundy','wine','red','brick'],colors:['#713f46','#6d8f8b','#d8c6a5'],labels:['Burgundy','Soft teal','Sand']},
{name:'Cream + rust + charcoal',keys:['cream','ivory','beige','stone'],colors:['#eee3cd','#a65f3e','#4f514f'],labels:['Cream','Rust','Charcoal']},
{name:'Black + muted gold + stone',keys:['black','charcoal','grey','gray'],colors:['#272726','#b59b61','#c9c0b1'],labels:['Black','Muted gold','Stone']},
{name:'Brown + moss + pale blue',keys:['brown','camel','tan','chocolate'],colors:['#7d6047','#788064','#b8c7ce'],labels:['Brown','Moss','Pale blue']},
{name:'Pink + chocolate + sage',keys:['pink','rose','blush'],colors:['#c98f93','#594039','#9da68d'],labels:['Dusty pink','Chocolate','Sage']},
{name:'White + cobalt + brick',keys:['white'],colors:['#f5f3ec','#365a91','#a6513f'],labels:['White','Cobalt','Brick']}
];

function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbGet(key){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const req=tx.objectStore(STORE).get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function dbSet(key,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(value,key);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function load(){try{const stored=await dbGet('state');if(stored){state=stored}else{const legacy=localStorage.getItem(LEGACY_KEY);if(legacy){state=JSON.parse(legacy);await dbSet('state',state);localStorage.setItem('eiram-closet-migrated','yes')}}}catch(e){console.warn('Storage load failed',e);try{const legacy=localStorage.getItem(LEGACY_KEY);if(legacy)state=JSON.parse(legacy)}catch{}}renderAll()}
async function save(){await dbSet('state',state);renderAll()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function switchView(name){views.forEach(v=>document.getElementById(v+'View').classList.toggle('active',v===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));screenTitle.textContent=titleMap[name];window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
addQuick.addEventListener('click',()=>openForm('closet'));document.querySelectorAll('[data-open-form]').forEach(b=>b.addEventListener('click',()=>openForm(b.dataset.openForm)));closeDialog.addEventListener('click',()=>itemDialog.close());
const form=itemForm,dialog=itemDialog,preview=photoPreview,picker=photoPicker;

async function compressImage(file,maxDim=1400,quality=.78){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error);reader.onload=()=>{const img=new Image();img.onerror=reject;img.onload=()=>{let w=img.width,h=img.height;if(w>maxDim||h>maxDim){const scale=Math.min(maxDim/w,maxDim/h);w=Math.round(w*scale);h=Math.round(h*scale)}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',quality))};img.src=reader.result};reader.readAsDataURL(file)})}
async function setPhoto(file){if(!file)return;if(!file.type.startsWith('image/')){alert('Please choose an image file.');return}photoHint.textContent='Optimising photo...';try{currentPhoto=await compressImage(file);preview.src=currentPhoto;picker.classList.add('has-photo');photoHint.textContent='Photo selected'}catch{alert('That photo could not be processed. Please try another image.')}}
galleryPhoto.addEventListener('change',e=>setPhoto(e.target.files?.[0]));cameraPhoto.addEventListener('change',e=>setPhoto(e.target.files?.[0]));
removePhoto.addEventListener('click',()=>{currentPhoto='';preview.removeAttribute('src');picker.classList.remove('has-photo');photoHint.textContent='No photo selected yet';galleryPhoto.value='';cameraPhoto.value=''});

function openForm(mode,item=null){form.reset();currentPhoto=item?.photo||'';itemMode.value=mode;editId.value=item?.id||'';formEyebrow.textContent=mode==='wishlist'?'ADD TO WISHLIST':'ADD TO CLOSET';formTitle.textContent=item?'Edit item':mode==='wishlist'?'Wishlist item':'New garment';['priceWrap','targetWrap','linkWrap'].forEach(id=>document.getElementById(id).style.display=mode==='wishlist'?'':'none');deleteItem.hidden=!item;if(item){itemName.value=item.name||'';itemCategory.value=item.category||'';itemColour.value=item.colour||'';itemSeason.value=item.season||'All-season';itemBrand.value=item.brand||'';itemSize.value=item.size||'';itemPrice.value=item.price||'';targetPrice.value=item.targetPrice||'';itemLink.value=item.link||'';itemNotes.value=item.notes||''}if(currentPhoto){preview.src=currentPhoto;picker.classList.add('has-photo')}else{preview.removeAttribute('src');picker.classList.remove('has-photo');photoHint.textContent='No photo selected yet'}dialog.showModal()}
form.addEventListener('submit',async e=>{e.preventDefault();const mode=itemMode.value,id=editId.value||uid();const data={id,owner:'You',name:itemName.value.trim(),category:itemCategory.value,colour:itemColour.value.trim(),season:itemSeason.value,brand:itemBrand.value.trim(),size:itemSize.value.trim(),photo:currentPhoto,notes:itemNotes.value.trim(),updatedAt:new Date().toISOString()};if(mode==='wishlist'){data.price=itemPrice.value;data.targetPrice=targetPrice.value;data.link=itemLink.value.trim();data.status='Watching'}const arr=state[mode],idx=arr.findIndex(x=>x.id===id);if(idx>=0)arr[idx]=data;else arr.unshift(data);try{await save();dialog.close()}catch(err){console.error(err);alert('Could not save this item. Please export a backup before trying again.')}});
deleteItem.addEventListener('click',async()=>{const mode=itemMode.value,id=editId.value;if(id&&confirm('Delete this item?')){state[mode]=state[mode].filter(x=>x.id!==id);await save();dialog.close()}});

function cardHtml(item,mode){const img=item.photo?`<img src="${item.photo}" alt="${esc(item.name)}">`:`<div class="item-photo-placeholder">${mode==='wishlist'?'♡':'◫'}</div>`;const price=mode==='wishlist'&&item.price?`<div class="price">€${esc(item.price)}${item.targetPrice?` · target €${esc(item.targetPrice)}`:''}</div>`:'';const styleBtn=mode==='closet'?`<button class="mini-action style-item" data-style-id="${item.id}">Style this item</button>`:'';return `<article class="item-card" data-mode="${mode}" data-id="${item.id}">${img}<div class="item-body"><h3>${esc(item.name)}</h3><p class="meta">${esc(item.category)}${item.colour?' · '+esc(item.colour):''}</p>${price}${styleBtn}</div></article>`}
function renderAll(){const q=(searchInput?.value||'').toLowerCase(),cat=categoryFilter?.value||'all';const filtered=state.closet.filter(x=>(cat==='all'||x.category===cat)&&(`${x.name} ${x.colour} ${x.brand}`.toLowerCase().includes(q)));closetGrid.innerHTML=filtered.map(x=>cardHtml(x,'closet')).join('');closetEmpty.style.display=filtered.length?'none':'block';wishlistGrid.innerHTML=state.wishlist.map(x=>cardHtml(x,'wishlist')).join('');wishlistEmpty.style.display=state.wishlist.length?'none':'block';document.querySelectorAll('.item-card').forEach(c=>c.addEventListener('click',e=>{if(e.target.closest('.style-item'))return;openForm(c.dataset.mode,state[c.dataset.mode].find(x=>x.id===c.dataset.id))}));document.querySelectorAll('.style-item').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();styleItem(b.dataset.styleId)}));const opts=state.closet.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');outfitSeed.innerHTML='<option value="">Choose an item</option>'+opts;wadaSeed.innerHTML='<option value="">Choose an item</option>'+opts}
searchInput.addEventListener('input',renderAll);categoryFilter.addEventListener('change',renderAll);

function colourGroup(c=''){const s=c.toLowerCase(),groups={neutral:['black','white','cream','ivory','beige','grey','gray','charcoal','stone'],blue:['navy','blue','indigo','cobalt','denim'],green:['green','olive','khaki','sage','moss'],red:['red','burgundy','wine','rust','brick'],brown:['brown','camel','tan','chocolate'],pink:['pink','rose','blush'],yellow:['yellow','ochre','mustard','gold'],purple:['purple','violet','plum']};return Object.entries(groups).find(([,a])=>a.some(k=>s.includes(k)))?.[0]||'other'}
function compatible(a,b){const ga=colourGroup(a),gb=colourGroup(b);if(ga==='neutral'||gb==='neutral')return true;const good={blue:['brown','yellow','red','pink','green'],green:['brown','pink','blue','neutral'],red:['blue','brown','neutral','pink'],brown:['blue','green','pink','neutral'],pink:['green','blue','brown','red'],yellow:['blue','brown','green'],purple:['green','yellow','neutral']};return(good[ga]||[]).includes(gb)}
function categoryRole(cat=''){if(['Tops','Knitwear'].includes(cat))return'top';if(cat==='Bottoms')return'bottom';if(cat==='Dresses')return'dress';if(cat==='Jackets')return'layer';if(cat==='Shoes')return'shoes';if(cat==='Accessories')return'accessory';return'other'}
function photoTile(item){return `<div class="outfit-piece">${item.photo?`<img src="${item.photo}" alt="${esc(item.name)}">`:`<div class="outfit-placeholder">◫</div>`}<div><strong>${esc(item.name)}</strong><span>${esc(item.category)}${item.colour?' · '+esc(item.colour):''}</span></div></div>`}
function scoreItem(seed,item){let score=compatible(seed.colour,item.colour)?3:0;if(colourGroup(seed.colour)==='neutral'||colourGroup(item.colour)==='neutral')score+=1;if(seed.season&&item.season&&(seed.season===item.season||seed.season==='All-season'||item.season==='All-season'))score+=1;return score}
function bestByRole(seed,role,limit=2){return state.closet.filter(x=>x.id!==seed.id&&categoryRole(x.category)===role).sort((a,b)=>scoreItem(seed,b)-scoreItem(seed,a)).slice(0,limit)}
function makeOutfits(seed){const role=categoryRole(seed.category),ideas=[];if(role==='dress'){const layers=bestByRole(seed,'layer',2),shoes=bestByRole(seed,'shoes',2),acc=bestByRole(seed,'accessory',1);for(let i=0;i<Math.max(layers.length,shoes.length,1);i++)ideas.push([seed,layers[i%Math.max(layers.length,1)],shoes[i%Math.max(shoes.length,1)],acc[0]].filter(Boolean))}else{const tops=role==='top'?[seed]:bestByRole(seed,'top',3),bottoms=role==='bottom'?[seed]:bestByRole(seed,'bottom',3),layers=bestByRole(seed,'layer',2),shoes=bestByRole(seed,'shoes',2);for(let i=0;i<3;i++){const look=[tops[i%Math.max(tops.length,1)],bottoms[i%Math.max(bottoms.length,1)],layers[i%Math.max(layers.length,1)],shoes[i%Math.max(shoes.length,1)]].filter(Boolean);if(role==='layer'&&!look.some(x=>x?.id===seed.id))look.unshift(seed);if(role==='shoes'&&!look.some(x=>x?.id===seed.id))look.push(seed);ideas.push([...new Map(look.map(x=>[x.id,x])).values()])}}return ideas.filter(x=>x.length>1).slice(0,3)}
function renderOutfits(seed){const ideas=makeOutfits(seed),missing=[],rolesPresent=new Set(state.closet.map(x=>categoryRole(x.category)));['top','bottom','layer','shoes'].forEach(r=>{if(!rolesPresent.has(r))missing.push(r)});outfitResults.innerHTML=`<div class="seed-banner">${photoTile(seed)}<div><span class="pill">Starting piece</span><p class="meta">Complete looks using your saved wardrobe.</p></div></div>${ideas.length?ideas.map((look,i)=>`<div class="outfit-card"><div class="outfit-card-head"><strong>Look ${i+1}</strong><span>${look.length} pieces</span></div><div class="outfit-strip">${look.map(photoTile).join('')}</div></div>`).join(''):`<div class="recommendation"><strong>Not enough complementary categories yet.</strong><p>Add a few tops, bottoms, layers or shoes and the outfit builder will become much stronger.</p></div>`}${missing.length?`<div class="recommendation"><strong>Wardrobe gap</strong><p class="meta">For fuller outfits, consider adding: ${missing.join(', ')}.</p></div>`:''}`}
function styleItem(id){const seed=state.closet.find(x=>x.id===id);if(!seed)return;switchView('outfits');outfitSeed.value=id;renderOutfits(seed)}
buildOutfit.addEventListener('click',()=>{const seed=state.closet.find(x=>x.id===outfitSeed.value);if(!seed){outfitResults.innerHTML='<div class="recommendation">Choose an item first.</div>';return}renderOutfits(seed)});
function wardrobeMatchesForPalette(seed,palette){const desiredGroups=palette.labels.map(colourGroup);return state.closet.filter(x=>x.id!==seed.id&&desiredGroups.includes(colourGroup(x.colour))).slice(0,6)}
showWada.addEventListener('click',()=>{const seed=state.closet.find(x=>x.id===wadaSeed.value);if(!seed){wadaResults.innerHTML='<div class="recommendation">Choose an item first.</div>';return}const c=(seed.colour||'').toLowerCase();let palettes=wadaPalettes.filter(p=>p.keys.some(k=>c.includes(k)));if(!palettes.length)palettes=wadaPalettes.slice(0,3);wadaResults.innerHTML=palettes.map(p=>{const matches=wardrobeMatchesForPalette(seed,p);return `<div class="recommendation"><strong>${esc(p.name)}</strong><div class="palette">${p.colors.map((c,i)=>`<div class="swatch-wrap"><div class="swatch" style="background:${c}"></div><small>${esc(p.labels[i])}</small></div>`).join('')}</div>${matches.length?`<p class="meta">Pieces you already own that may work with this direction:</p><div class="mini-strip">${matches.map(photoTile).join('')}</div>`:`<p class="meta">You do not have an obvious matching piece recorded yet. This can be useful as a wishlist colour direction.</p>`}</div>`}).join('')});

exportBackup.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:2,storage:'indexeddb',exportedAt:new Date().toISOString(),data:state},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='eiram-closet-backup.json';a.click();URL.revokeObjectURL(a.href)});
importBackup.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const x=JSON.parse(r.result);if(!x.data)throw new Error();state=x.data;await save();alert('Backup restored.')}catch{alert('That backup file could not be read.')}};r.readAsText(f)});
if('storage' in navigator&&'persist' in navigator.storage)navigator.storage.persist().catch(()=>{});
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
load();
